export const RouteMap = {
  AuthStack: 'AuthStack',
  AppStack: 'AppStack',
  TabStack: 'TabStack',
  Home: 'Home',
  Signin: 'Signin',
  Signup: 'Signup',
  ForgotPassword: 'ForgotPassword',
  PostDetails: 'PostDetails',
  AddEditPost: 'AddEditPost',
  MemberDetails: 'MemberDetails',
  Account: 'Account',
  EditProfile: 'EditProfile',
  JobExperiences: 'JobExperiences',
  AddEditExperience: 'AddEditExperience',
  ChangePassword: 'ChangePassword',
  CommitteeDetails: 'CommitteeDetails',
  Profile: 'Profile',
  Settings: 'Settings',
  Notifications: 'Notifications',
  About: 'About',
  TermsOfService: 'TermsOfService',
  PrivacyPolicy: 'PrivacyPolicy',
  Member: 'Member',
  Committee: 'Committee',
};
